// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_mmap   22
#define SYS_munmap 23
#define SYS_svprint  24
#define SYS_trace  25
#define SYS_sysinfo 26
#define SYS_sbrknaive 27
#define SYS_dirtypages  28
#define SYS_vmprint  29
#define SYS_pgaccess  30
#define SYS_sigalarm  31
#define SYS_sigreturn 32
#define SYS_testbacktrace 33
#define SYS_clone  34
#define SYS_join   35
#define SYS_connect   36
#define SYS_recvfrom  37
#define SYS_sendto    38
#define SYS_accept    39
#define SYS_symlink  40
#define SYS_sigsend  41
#define SYS_signal  42
#define SYS_sigprocmask  43
